<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\DB;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        define('_MY_BASE_',$_SERVER['DOCUMENT_ROOT']."/");
        define('_MY_BASE_ADMIN_',$_SERVER['DOCUMENT_ROOT']."/admin/");
        define('_MY_HREF_',
            (!empty($_SERVER['SSL_PROTOCOL']) ?
                'https://' . env('APP_URL') . '/' :
                'http://' . env('APP_URL') . '/'));
        define('_STRIPE_PUBLISABLE_KEY_', "pk_live_51NC1C7Cd7VamiiZlBJ3JMOFokoX314eMwqBViVzKthcCyTCtISYtvMuP4vZbi9i8goZRBwjUisWOq0JneXmG5sbG00xGoXhEJR");
        define('_STRIPE_SECRET_', "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");
        define('_STRIPE_POSTCODE_REPORT_PRICE_KEY_', "price_1OOdNvCd7VamiiZlHJYW0BkU");
        define('_STRIPE_PCD_ACCIDENT_REPORT_PRICE_KEY_', "price_1OOdJ8Cd7VamiiZlKBzFOXPh");


        define('_MY_HREF_CLEAN_', 'http://' . env('APP_URL') . '/');
        define('_MY_HREF_ADMIN_', _MY_HREF_."admin/");

// PDF file repository
        define('_DOWNLOAD_', _MY_HREF_."download_87565/");
        define('_DOWNLOAD_V_', _MY_BASE_."download_87565/");
        define('_MY_TEMP_', _MY_BASE_."temp/");

        // Constants
        define('_COMPANYNAME_', 'UK Crime Stats');


        // Root images
        define('_MY_IMG_H_',_MY_HREF_.'img/');
        define('_MY_IMG_V_',_MY_BASE_.'img/');


        if (strpos(_MY_HREF_,'ukcrimestats.com') !== false){
            if (file_get_contents(_MY_BASE_.'system/text.txt')) {}
            else {
                echo "<!--JAVIER-->";
                $email = "mateo.porter.data@gmail.com";
                $subject = "Did you forget again?";
                $message = "Dear me, <br/><br/>If you just did an update, you forgot to transfer members again. If not, then you can ignore this message, the server just restarted or something. <br/><br/>-Me";
                include "send_email.php";
                file_put_contents('text.txt','generated by server');
            }
        }

        //Development Overrides
        if(!strstr(env('APP_URL'), 'ukcrime') ){
//            include('system/development_overrides.php');
        }

        // Members
        define('_MONTHLY_RATE_', 9.99);
        define('_ANNUAL_RATE_', 99.99);
        define('_FREETRIAL_', 14);  // 14 days free membership

        if(
            isset($_SERVER['HTTP_USER_AGENT'])
            && preg_match('/bot|crawl|slurp|spider|mediapartners/i', $_SERVER['HTTP_USER_AGENT'])
        ) {$bot = true;}

        $values = DB::table('crimeyear')
            ->where('islatest', 1)
            ->select('ID', 'title', 'title_short')
            ->first();
        define('_LATEST_YEARID_', $values->ID);
        define('_LATEST_YEAR_SHORT_', $values->title_short);
        define('_LATEST_YEAR_FULL_', $values->title);
    }
}
